### ISSUE TITLE
Improve test generators

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#356]
- [x] Render `null` as `null` without requiring wrapping in an unescaped values
- [x] Use `Assert.Null` if using `Assert.Equal(null, x)`
- [x] Don't render quote character in test method/class names

**Comment by robkeim** [comment]
Nice work @jpreese getting these issues fixed! Are there any other issues we've discovered so far that we should be tracking here, or should we go ahead and close this issue?

**Comment by ErikSchierboom** [comment]
I think we can close.

**Comment by jpreese** [comment]
Yeah it depends if we want to keep this as a rolling issue and keep adding to it, or just close it out and open PRs as we find stuff. I'm a fan of the latter since I don't really like issues that just never have a clear finish line.

I have a couple other ideas, but I was just going to do PRs for them, so I'll go ahead and close this.
