### ISSUE TITLE
Hacktoberfest preparation

### ISSUE THREAD

**Issue by jpreese** [exercism/csharp#396]
Discussion has been starting around Hacktoberfest over in the discussions repository (https://github.com/exercism/discussions/issues/190).

I just wanted to gather everyone's thoughts they may relate specifically to the csharp repository. I found a couple things relating to grammatical/spelling which should be easy grabs for the event. 

Easy stuff we can make tickets for:
Capitalize w in hello world snippet.txt
"It the output" inside of installation.md
"want to to" inside of installation.md

Though more advanced work isn't exactly clear to me at the moment. Mostly what I can think of is going to be refactoring the generator project. Maybe we could close the giant generator support and spawn individual tickets?

**Comment by robkeim** [comment]
@jpreese thanks for bringing up this discussion!

In terms of what we want to have as issues I think that it depends on who we want to attract in terms of contributions. The "capitalize the we in hello world snippet.txt" would be great for someone that's never contributed to open source before and wants to learn about GitHub, pull requests, etc, but for any seasoned developer that's not going to be interesting for them and you're going to probably spend more time creating that ticket than whoever actually fixes it :)

I'd be all for closing the giant generator support ticket and having multiple individual tickets for each exercise now that the remaining exercises is down to a "reasonable" number. Implementing a test generator is definitely something we could use help on, and it provides an interesting technical challenge, so I think those are good candidates for people with more experience.

In terms of what else we want to get done, I feel that in the current state the C# track is actually in pretty good shape. We've already got all available exercises implemented and once we get the generators finished the technical debt should be low and the track easy to maintain 🎉 

Here are some potential ideas:
- Upgrade to dotnetcore 2.0 (@ErikSchierboom should be able to provide more details on what advantages that would bring if any)
- Add the exercises without canonical data to the generator -> Right now we have to manually check to see if an exercise gets canonical data in the future. I'd like to have it integrated into the generator with some sort of flag saying "this doesn't have data" and then it can start throwing exceptions in the future if the data is created so we know we'll have to implement it (keeping my fingers crossed that all exercises will have canonical data someday)
- Cleanup the existing open tickets that we have -> a few of them are documentation only which isn't going to be the most enticing work unfortunately
- Is there anything that we need to do as a track for v2 of the website? I know the main discussion (https://github.com/exercism/discussions/issues/190) says there won't be any work on the v2 site itself because it's not ready yet, but if there's work that we'll need to do on an individual track level that would be a useful contribution

**Comment by jpreese** [comment]
As far as attracting, I think its really going to be all backgrounds. People newer to GitHub / development are going to be all over those spelling error ones. Those who might come from a more technical writing background might be hunting down documentation tickets. Just giving people options.

I think the generators are going to be our best selling points for the event. We have quite a few left, and if we split them into individual tickets, labeled them all with hacktoberfest, we can keep discussions separate and help people get through them on a generator by generator basis. We'll also want to finish up the ticket we have in regards to how to add a generator, why we generate, etc. Try to educate people as much as possible to answer any of the easy questions. (https://github.com/exercism/csharp/issues/264)

As far as v2, I think we've done everything already. We've updated our maintainers, about page, etc..

**Comment by ErikSchierboom** [comment]
> Maybe we could close the giant generator support and spawn individual tickets?

Absolutely!

> Easy stuff we can make tickets for:
Capitalize w in hello world snippet.txt
"It the output" inside of installation.md
"want to to" inside of installation.md

I'm actually in favor of creating separate issues for these small typos, as they are great for new people to get their feet wet in the Hacktoberfest.

> Upgrade to dotnetcore 2.0 (@ErikSchierboom should be able to provide more details on what advantages that would bring if any)

Well, there are actually two parts: one is using .NET CLI 2.0 and one is using `netcoreapp2.0` in our projects. For the first, we only need to change the documentation a little bit. Using .NET CLI 2.0 will give users the following benefits:

1. You can just run `dotnet test` to run the tests. The `dotnet restore` command is no longer needed. Not
2. The .NET CLI 2.0 appears to be a bit faster than version 1.x

Upgrading to `netcoreapp2.0` allows the user to access far more API's than `netcoreapp1.x`, but I don't think people need those API's to solve our exercises. The main disadvantage is that you then would have to have .NET CLI 2.0 installed, as it won't work on .NET CLI 1.x. I think we should, at least for the moment, not upgrade our projects to `netcoreapp2.0` to allow people to also use .NET CLI 1.x. However, we should update the documentation for .NET CLI 2.0 to show them the simpler usage.

> Add the exercises without canonical data to the generator -> Right now we have to manually check to see if an exercise gets canonical data in the future. I'd like to have it integrated into the generator with some sort of flag saying "this doesn't have data" and then it can start throwing exceptions in the future if the data is created so we know we'll have to implement it (keeping my fingers crossed that all exercises will have canonical data someday)

Ooh, I like this idea! Very nice!

> Cleanup the existing open tickets that we have -> a few of them are documentation only which isn't going to be the most enticing work unfortunately

+1

> Is there anything that we need to do as a track for v2 of the website? I know the main discussion (exercism/discussions#190) says there won't be any work on the v2 site itself because it's not ready yet, but if there's work that we'll need to do on an individual track level that would be a useful contribution

> As far as v2, I think we've done everything already. We've updated our maintainers, about page, etc..

Well actually, there is an open issue to [improve our ABOUT page](https://github.com/exercism/csharp/issues/367), which can be more detailed and enticing than what we have now.

**Comment by jpreese** [comment]
Hacktoberfest signups are out!
