### ISSUE TITLE
Update song exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#493]
There are multiple song-related exercises:

- `house`
- `beer-song`
- `twelve-days`
- `proverb`
- `food-chain`

These exercise have all been updated to have a similar structure. This includes having the return value be an array of strings, instead of a big string. We should decide if we want to follow that approach or still use strings. What do you think?

**Comment by robkeim** [comment]
I'm usually a fan of following the canonical data (where it makes sense), but I didn't read the entire thread on *why* they changed to the array format to represent these instead of a single string. @ErikSchierboom do you know?

My gut feel would be that having a string seems more natural but I don't have a strong enough argument for that to convince myself it's worth straying away from the canonical data. I could definitely be convinced that's the right direction to go in though :)

**Comment by ErikSchierboom** [comment]
I don't recall exactly why the array approach was chosen. I'm not really for or against an approach, although in the F# track I've used lists for the expected result, not strings.

**Comment by robkeim** [comment]
In that case I'd say let's go with the path of least resistance :)

From a student perspective I think the array approach might be *slightly* more difficult, but nothing considerable. How about in terms of maintenance for us?

**Comment by ErikSchierboom** [comment]
I don't think it matters much :)

**Comment by ErikSchierboom** [comment]
I'm working on this
