### ISSUE TITLE
Changed Unit tests confuses code reviewing and code commentary

### ISSUE THREAD

**Issue by martinfreedman** [exercism/csharp#513]
For example Erik see my comment on your solution to TwoBuckets. 

Just want some way to know that exercise was completed for some old(er) test suite.

**Comment by ErikSchierboom** [comment]
Well, some exercises are nowadays created using a test data generator, which automatically includes the version of the canonical data in the header: https://github.com/exercism/csharp/blob/master/exercises/atbash-cipher/AtbashCipherTest.cs#L1

But we should indeed also add something like that to non-generator exercises, which is why I created #514.

**Comment by martinfreedman** [comment]
Agreed
