### ISSUE TITLE
Add binary-search-tree generator

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#536]
If you want to implement this exercise, please note that you need to ensure the test cases are generated based on the input.

Here's the exercise description:
https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/description.md

Here's the test case data:
https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/canonical-data.json

**Comment by ShamilS** [comment]
@ErikSchierboom  I'm taking it. I'll try to make it ready within this week.

**Comment by ShamilS** [comment]
@ErikSchierboom Do you have a ref on a sample generator generating

using System.Linq;

in the header area of the generated test class?

**Comment by ShamilS** [comment]
@ErikSchierboom [PR is here.](https://github.com/exercism/csharp/pull/558)

P.S. I should have published/referred the PR in this issue "automagically"? If yes, - how such a PR publication should have been done?

**Comment by ErikSchierboom** [comment]
@ShamilS No need, we automatically get a notification when there is a new PR.

**Comment by robkeim** [comment]
Fixed by https://github.com/exercism/csharp/pull/558

@ShamilS If you'd like you can link the issue you're resolving from the PR with something like:
`Fixes #XXX`

Where XXX is replaced with the issue number (536 for this one). That will link the PR and issue and when the PR gets merged will close the issue automatically.

**Comment by ShamilS** [comment]
@robkeim  OK
