### ISSUE TITLE
dependabot: allow automatic merging of minor and patch bump

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#983]
@robkeim I've noticed the following text in one of the automatic PR's:

> Additionally, you can set the following in the `.dependabot/config.yml` file in this repo:
> 
> * Update frequency (including time of day and day of week)
> * Automerge options (never/patch/minor, and dev/runtime dependencies)
> * Pull request limits (per update run and/or open at any time)
> * Out-of-range updates (receive only lockfile updates, if desired)
> * Security updates (receive only security updates, if desired)

Maybe we could configure and automerge option for patch/minor updates, provided that the PR succeeds?

**Comment by robkeim** [comment]
That sounds like a good idea to me! I'll look into it

**Comment by robkeim** [comment]
@ErikSchierboom here's a manual test for accumulate:
https://github.com/exercism/csharp/pull/984

If that works well then I'll update the script and expand this for the rest of the exercises.

Please don't merge the accumulate PRs from dependabot as I'd like to use them to see if this auto-merge works correctly (although it might be too late since they've already been created).
